apply plugin: 'com.android.application'

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localProperties.load(new FileInputStream(localPropertiesFile))
}

def mapsApiKey = localProperties.getProperty('MAPS_API_KEY') ?: ""
def baseUrl = localProperties.getProperty('BASE_URL') ?: ""

android {
    namespace "com.iggresserver.datacollection"
    compileSdkVersion 34
    defaultConfig {
        applicationId "com.iggresserver.datacollection"
        minSdkVersion 21
        targetSdkVersion 34
        versionCode 5
        versionName "1.1"
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
        multiDexEnabled true

        manifestPlaceholders = [mapsApiKey: mapsApiKey]
        buildConfigField "String", "BASE_URL", "\"${baseUrl}\""
        buildConfigField "String", "MAPS_API_KEY", "\"${mapsApiKey}\""
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        buildConfig true
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.media:media:1.7.0'
    implementation 'androidx.dynamicanimation:dynamicanimation:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'

    implementation 'com.karumi:dexter:6.2.3'
    implementation 'com.google.android.gms:play-services-maps:18.2.0'
    implementation 'com.github.mancj:MaterialSearchBar:0.8.5'
    implementation 'com.google.android.libraries.places:places:3.5.0'
    implementation 'com.skyfishjy.ripplebackground:library:1.0.1'

    implementation 'com.makeramen:roundedimageview:2.3.0'
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'com.github.iammert:ReadableBottomBar:0.2'
    implementation 'com.android.volley:volley:1.2.1'
}
